import random
import time

game = ["Doom Eternal",
        "Banjo-Kazooie",
        "Altered Beasts",
        "Battletoads",
        "Goat Simulator", 
        "Viva Piñata: Trouble in Paradise",
        "Bioshock",
        "Lego Island",
        "007: Nightfire",
        "Zoombinis",
        "Myst",
        "Pokémon Snap",
        "Half-Life 3",
        "E.T. the Extra-Terrestrial",
        "Mario Paint",
        "Rhythm Heaven: Fever",
        "Mister Mosquito",
        "Oddworld: Abe's Oddysee",
        "Space Giraffe",
        "Michael Jackson’s Moonwalker",
        "Clay Fighter 63 1/3",
        "Superman 64",
        "Zelda: The Wand of Gamelon",
        "Hotel Mario",
        "Shaq Fu",
        "The Bugs Bunny Birthday Blowout",
        "Rollercoaster Tycoon",
        "Bible Adventures",
        "Jet Force Gemini",
        "Escape from Monkey Island",
        "A Boy and His Blob"]

rq_response = ["It is certain.",
                "Dude, I don't fucking know.",
                f"Hmm...\nYea, I still don't know",
                "Are you seriously talking to a chatbot?",
                "Sure, why not...",
                "If this is a yes or no question, then no.",
                "Really? Are we playing 21 questions?",
                "Let me ask you a question instead."]

sent_it =     ["https://youtu.be/UfjB5ktSLAU",
               "https://youtu.be/jM0GePXOdT0",
               "https://youtu.be/HPGoUbjJlcc",
               "https://youtu.be/89KcuiXDKb4",
               "https://youtu.be/wEne1zi0CnQ",
               "https://youtu.be/j-xetx9XxpQ",
               "https://youtu.be/X8avbciUP3c",
               "https://youtu.be/mefAsS7L37A",
               "https://youtu.be/LE0fzQGo9l0",
               "https://youtu.be/HNcpuJ5mkhQ",
               "https://youtu.be/3E4xAlzt8m8",
               "https://youtu.be/kMV3A_28a0I",
               "https://youtu.be/MKE5Cl8qiU4",
               "https://youtu.be/VvlqWVdQ-zs",
               "https://youtu.be/hqD0c4nSvB8",
               "https://youtu.be/xgrqhuwydDk",
               "https://youtu.be/j-xetx9XxpQ",
               "https://youtu.be/aE0bNiHRUso",
               "https://youtu.be/swPu3-YjxIU",
               "https://youtu.be/1Z-M8y1c8AQ",
               "https://youtu.be/AhcKn0dSjtE",
               "https://youtu.be/FMKcPao7A6Y",
               "https://youtu.be/FuX5_OWObA0",
               "https://youtu.be/ZHJBL902XKM",
               "https://youtu.be/dg1CE0ae_wU",
               "https://youtu.be/OqLVc7PbdoY",
               "https://youtu.be/nzhD2edY3mQ",
               "https://youtu.be/6G8YCM0pGfU",
               "https://youtu.be/us5MGEL5W34"]
